# Generated by Django 4.0 on 2021-12-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genomafoodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('ubication', models.TextField()),
                ('food_type', models.TextField()),
                ('score', models.IntegerField()),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
    ]
