# Generated by Django 4.0 on 2021-12-29 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomafoodies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomafoodies',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='genomafoodies',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
